routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/{user_slug}', 'Shopper@index');
Route::get('/modal-checkout/{article_id}/{shopper_id}','Shopper@modalCheckOutBody');
Route::get('/thank-you/{order_id}','Shopper@thankYou');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
  protected $table = 'articles_photo';
  protected $primaryKey = 'id_photo';

  public function getPathAttribute($value)
  {
    return 'http://www.andresfashiongroup.com/'.$value;
  }

}

resources/views/sections/home.blade.php
<style media="screen">
.shopper-cover{
  height: 320px;
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center center;
}
.shopper-board{
  margin-top: -120px;

  background: rgba(255,255,255,0.6);
  padding: 18px;
}
</style>
<div class="shopper-cover" style="background-image:url('http://www.andresfashiongroup.com/{{$shopper->cover_image}}')"></div>
<div class="shopper-board container">
    <div class="row">
      <div class="col-md-4 text-center">
        <div class="shopper-avatar-wrapper">
          <div class="shopper-avatar">
            <img src="http://www.andresfashiongroup.com/{{$shopper->avatar_image}}" alt="">
          </div>
        </div>
      </div>
      <div class="col-md-6 ">
        <h1 class="shopper-nickname">{{$shopper->shopper_nickname}}</h1>
        <div class="row shopper-info">
          <div class="col-md-4">
            <b>{{count($products)}}</b> products
          </div>
          <div class="col-md-4">
            <b>{{$count_sales}}</b> sales
          </div>
          <div class="col-md-4">
            <b>{{$count_followers}}</b> followers
          </div>
        </div>
        <p class="shopper-description">{{$shopper->shopper_description}}</p>
      </div>
    </div>

</div>
<div class="container">
  <div class="row">
    <div class="d-none">
      <pre>
        <?php print_r($products)?>
      </pre>
    </div>
    <!-- Set all conditions to include product thumbnail -->
    @foreach($products as $product)
    @if(!is_null($product->brand))
    @include('sections.product_thumb')
    @endif
    @endforeach
  </div>
</div>

resources/views/sections/product_thumb.blade.php
<div class="col-md-4 pt">
  <a href="javascript:" onclick="api.openCheckoutModal({{$product->article_id}})">
    <div class="pt-header">

    </div>
    <div class="pt-body">
      <div class="pt-body-overlay">
        <div class="text-center">
          <h2>{{$product->brand->brand_name}}</h2>
          <p class="desc">{{$product->description}}</p>
          @if(count($product->best_price)>0)
          <p class="price">{{$currency}} {{number_format($product->best_price[0]->value,2)}}</p>
          @endif
        </div>

      </div>
      <div class="pt-body-image-wrapper">
        <img src="{{$product->photos[0]->path}}" alt="">
      </div>
    </div>
    <div class="pt-footer">

    </div>
  </a>
</div>